---
title: "Hector general summary"
author: "Leeya Pressburger"
date: "9/29/2021"
output:
  html_document:
    toc: yes
    toc_float: true
---

## Introduction to Hector
Hector is an open source, object-oriented, simple global carbon cycle model. As a simple climate model, Hector runs very quickly while still representing the most critical global earth system processes. Hector is the default carbon cycle module for the integrated assessment model GCAM (Global Change Assessment Model). Its open-source nature and modular design allows the user to edit input files and code, meaning a user could design a new submodel to answer a particular science question. Hector can accurately reproduce historical trends and future projections of atmospheric CO~2~, radiative forcing, and global temperature change under the four RCPs^[Hartin, C. A., Patel, P., Schwarber, A., Link, R. P., and Bond-Lamberty, B. P. (2015). A simple object-oriented and open-source model for scientific and policy analyses of the global climate system – Hector v1.0, Geosci. Model Dev., 8, 939–955. https://doi.org/10.5194/gmd-8-939-2015.] and SSPs.

Hector contains a well-mixed global atmosphere, an ocean component, and a land component composed of vegetation, detritus, and soil. Briefly, terrestrial vegetation, detritus, and soil are linked with each other and the atmosphere by first-order differential equations. Carbon flows from vegetation to detritus to soil, losing fractional amounts to heterotrophic respiration. For more details on the terrestrial carbon cycle, please reference ["The model's terrestrial carbon cycle"](https://jgcri.github.io/hector/articles/manual/SimpleNBox.html). Note that Hector's fundamental time step is one year, but the carbon cycle can be scaled to a finer resolution if necessary.^[Hartin et al., 2015.] The ocean component consists of four boxes: two surface boxes, one high-latitude and the other low-latitude, one intermediate, and one deep box. The cold high-latitude (>55$^◦$) box makes up 15% of the ocean surface area and the warm low-latitude box (>55$^◦$) makes up the remaining 85%. Ocean temperatures are linearly related to the global atmospheric temperature change; this temperature gradient causes a flux of carbon into the high-latitude box and a flux of carbon out of the warm low-latitude box.^[Vega-Westhoff, B., Sriver, R. L., Hartin, C. A., Wong, T. E., & Keller, K. (2019). Impacts of observational constraints related to sea level on estimates of climate sensitivity. Earth's Future, 7, 677– 690. https://doi.org/10.1029/2018EF001082]

Hector can also calculate near surface global atmospheric temperature. Radiative forcing is calculated from various atmospheric greenhouse gases, aerosols, and pollutants, including halocarbons, tropospheric ozone, black and organic carbon, sulfate aerosols, methane (CH~4~), nitrous oxide (N~2~0), and stratospheric H~2~0 from methane oxidation.^[Hartin et al., 2015] 

Hector v2.0 replaced the temperature component of the model with the coupled 0-D climate and 1-D ocean heat diffusion model, DOECLIM. The Hector implementation, like other past assessments using DOECLIM, has three tuneable physical parameters: equilibrium climate sensitivity to a doubling of CO~2~, vertical ocean diffusivity, and an aerosol forcing scaling factor. This addition improved vertical ocean structure and heat uptake as well as the surface temperature response to radiative forcing. Additionally, Hector V2.0 incorporates a semiempirical model based on global temperature to calculate global sea level change. This component is based on the BRICK model framework, where global sea level changes are treated as the sum of contributions from thermal expansion, glaciers and small ice caps, the Greenland and Antarctic ice sheets, and changes in land water storage. BRICK has been updated within Hector to simplify coupling.^[Vega-Westhoff et al., 2019] 

## Other simple climate models

Simple climate models, also referred to as reduced-complexity climate models, represent only the most critical global-scale earth system processes with low spatial and temporal resolution. These models are relatively easy to use or understand and are computationally less expensive and time-consuming than more complex earth system models. Most simple climate models calculate future concentrations of greenhouse gases from given emissions while modeling the global carbon cycle, calculate global mean radiative forcing from greenhouse gas concentrations, and convert the radiative forcing to global mean temperature.^[Hartin et al., 2015] 

Other simple climate models include, although are not limited to, the following:
* [ACC2](https://doi.org/10.1007/s10584-009-9566-6): The Aggregated Carbon Cycle, Atmospheric Chemistry, and Climate model
* [AR5IR](https://doi.org/10.5194/acp-13-1853-2013): The Fifth Assessment Report Impulse Response Model
* [CICERO-SCM](http://hdl.handle.net/11250/192444): The CICERO Simple Climate Model
* [EMGC](https://doi.org/10.5194/acp-13-3997-2013): The Empirical Model of Global Climate
* [ESCIMO](https://doi.org/10.5194/esd-7-831-2016): The Earth System Climate Interpretable Model
* FaIR-v1-5 and FaIR-v2-0-0: The Finite-amplitude Impulse Response
* [GENIE](https://www.ercim.eu/publication/Ercim_News/enw61/price.html): Grid Enabled Integrated Earth System Model
* [GREB](https://doi.org/10.1007/s00382-011-1026-0): The Globally Resolved Energy Balance model, also referred to as the Monash Simple Climate Model
* [MAGICC](http://www.magicc.org/): The Model for the Assessment of Greenhouse Gas Induced Climate Change
* [MARGO](https://doi.org/10.31223/osf.io/5bgyc): MARGO represents four potential climate controls, emissions Mitigation, carbon dioxide Removal, Geo-engineering, and Adaptation.
* [MCE](https://doi.org/10.5194/gmd-2021-79): A minimal CMIP emulator
* [OSCAR](https://doi.org/10.5194/gmd-10-271-2017): a simple earth system model and non-linear box model
* [RDCEP](http://www.rdcep.org/research-projects/climate-emulator): The Center for Robust Decision-making on Climate and Energy Policy created a statistical climate emulator.
* [WASP](https://doi.org/10.1007/s00382-015-2960-z): The Warming Acidification and Sea level Projector

## Further information
Please see the documentation manuscripts:   

1. [Hector v1](https://doi.org/10.5194/gmd-8-939-2015):  
    Hartin, C. A., Patel, P., Schwarber, A., Link, R. P., and Bond-Lamberty, B. P. (2015). A simple object-oriented and open-source model for scientific and policy analyses of the global climate system – Hector v1.0, Geosci. Model Dev., 8, 939–955. https://doi.org/10.5194/gmd-8-939-2015
    
2. [Hector v1.1](https://doi.org/10.5194/bg-13-4329-2016):  
    Hartin, C. A., Bond-Lamberty, B. P., Patel, P., and Mundra, A. (2016). Ocean acidification over the next three centuries using a simple global climate carbon-cycle model: projections and sensitivities, Biogeosciences, 13, 4329 – 4342. https://doi.org/10.5194/bg-13-4329-2016
    
3. [Hector v2.0](https://doi.org/10.1029/2018EF001082):  
    Vega-Westhoff, B., Sriver, R. L., Hartin, C. A., Wong, T. E., & Keller, K. (2019). Impacts of observational constraints related to sea level on estimates of climate sensitivity. Earth's Future, 7, 677– 690. https://doi.org/10.1029/2018EF001082
