---
title: "Authorship Guidelines"
---

As mentioned in our [contribution guide](ContributionsGuide.html), “the Hector team welcomes and values community contributions to Hector” and would like to acknowledge these contributions. To be fully transparent here are the guidelines we use to determine authorship for the Hector model. 

* The author list reflects individuals that contributed code (either R code in support of the R Hector package and/or C++ Hector source code) to a specific version of Hector. 
* The author list is not a running list of all Hector contributors over the years. In general, individuals on the author list have made major code contributions to either the current or the immediately previous version of the model. 
* We recognize contributors to older versions of the model via the table of past contributors (see below) 
This author list does not include contributors to other Hector-related software such as HectorUI or Hectordata. The list also does not credit authorship for generating model development ideas, analysis, and so on. This category of credit occurs in manuscripts focused on model documentation or analyses using Hector. 

**Past Contributors**

```{r, echo=FALSE, warning =FALSE}

dat <- rbind(c("Robert Link", "0000-0002-7071-248X", " < 2.5", "Wrapped the Hector cpp source code into a R package"), 
      c("Corinne Hartin", "0000-0003-1834-6539", " < 2.0", "Wrote the original ocean component"))
colnames(dat) <- c("Contributor", "ORCID", "Version", "Contribution")

knitr::kable(dat, format = "markdown")
```


