---
title: "Hector's Climate"
---

## Science

**Hector** is an open source, object-oriented, simple global climate carbon-cycle model. Greenhouse gases (GHGs) and aerosols are emitted into the atmosphere, where the GHGs accumulate. The GHG concentrations and aerosol emissions impact the Earth's radiative forcing budget. Hector's temperature component (which is based on DOECLIM^[Kriegler, E. (2005). Imprecise probability analysis for integrated assessment of climate change. Ph.D. thesis. Potsdam URL: Universit t
Potsdam. https://www.pik‐potsdam.de/members/edenh/theses/PhDKriegler.pdf], a diffusion ocean-energy balance) uses total radiative forcing to calculate mean global air temperature from sea-surface and land-surface temperature anomalies. Hector returns global mean air surface temperate (GMAT), land surface temperature, and ocean surface temperature which can be used to calculate global mean surface temperature (see [here](GMAT-GMST.html) for more details). DOECLIM simulates the different rates of warming over land and ocean surfaces global mean surface temperature, meaning that the land-ocean warming ratio is an emergent property of Hector. However, users do have the option to provide a land-ocean warming ratio to be used in place of DOECLIM’s internal calculations (see [here](land_ocean_warming.html) for an example and more details about this feature).

## Implementation

1. Emissions are read into Hector by their Hector components where they are prepared to be passed to the `forcing_component`. For example, black carbon (BC) emissions are read into Hector by the `bc_component` whereas methane emissions are read in by `ch4_component`. The aerosol components (`bc_component`,`oc_component`, `so2_component`, and `nh3_component`) can directly pass the emissions to the `forcing_component` whereas GHG emissions such as methane must first be converted to concentrations.  
2. Effective radiative forcing for each GHG concentration and aerosol is calculated based the IPCC AR6^[Smith, C., Z. R. J. Nicholls, K. Armour, W. Collins, P. Forster, M. Meinshausen, M. D. Palmer, M. Watanabe. 2021. “The Earth’s Energy Budget, Climate Feedbacks, and Climate Sensitivity Supplementary Material.” In Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change, edited by Masson-Delmotte, V., P. Zhai, A. Pirani, S. L. Connors, C. P an, S. Berger, N. Caud, Y. Chen, L. Goldfarb, M. I. Gomis, M. Huang, K. Leitzell, E. Lonnoy, J.B.R. Matthews, T. K. Maycock, T. Waterfield, O. Yelek i, R. Yu and B. Zhou. https://ipcc.ch/static/ar6/wg1.]. Additional sources of radiative forcing such changes in land albedo and volcanoes are added together to determine the total change in radiative forcing within the `forcing_component`. 
3. The `forcing_component` passes total radiative forcing to the `temperature_component` where DOECLIM^[Kriegler, E. (2005). Imprecise probability analysis for integrated assessment of climate change. Ph.D. thesis. Potsdam URL: Universit t
Potsdam. https://www.pik‐potsdam.de/members/edenh/theses/PhDKriegler.pdf], a diffusion ocean-energy balance model, determines how the change in Earth's radiative forcing budget manifests as changes in mean global air temperature from sea-surface and land-surface temperature anomalies. 

Important note: for atmospheric CO~2~, the carbon cycle must be solved before Hector is able to calculate radiative forcing from CO~2~ because the temperature effects from CO~2~ are lagged in time. 
