# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create and initialize a new hector instance
#'
#' The object returned is a handle to the newly created instance.  It will be required as an
#' argument for all functions that operate on the instance.  Creating multiple instances
#' simultaneously is supported.
#'
#' @param infile (String) name of the hector input file.
#' @return handle for the Hector instance.
#' @export
newcore <- function(inifile) {
    .Call('_hector_newcore', PACKAGE = 'hector', inifile)
}

#' Shutdown a hector instance
#'
#' Shutting down an instance will free the instance itself and all of the objects it created. Any attempted
#' operation on the instance after that will raise an error.
#'
#' @section Caution:
#' This function should be called as \code{mycore <- shutdown(mycore)} so that the change
#' from active to inactive will be recorded in the caller.
#'
#' @param Handle to the Hector instance that is to be shut down.
#' @return The Hector handle, modified to show that it is no longer active.
#' @export
shutdown <- function(core) {
    .Call('_hector_shutdown', PACKAGE = 'hector', core)
}

#' Run the Hector climate model
#'
#' Run Hector up through the specified time.  This function does not return the results
#' of the run.  To get results, run \code{fetch}.
#'
#' @param core Handle a Hector instance that is to be run.
#' @param runtodate Date to run to.  The default is to run to the end date configured
#' in the input file used to initialize the core.
#' @export
run <- function(core, runtodate = -1.0) {
    invisible(.Call('_hector_run', PACKAGE = 'hector', core, runtodate))
}

#' Get the current date for a Hector instance
#'
#' The "current date" is the last year that the Hector instance has completed.
#'
#' @param core Handle to a Hector instance
#' @return The current date in the Hector instance
#' @export
getdate <- function(core) {
    .Call('_hector_getdate', PACKAGE = 'hector', core)
}

