# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MSG_GETDATA <- function() {
    .Call('_hector_MSG_GETDATA', PACKAGE = 'hector')
}

MSG_SETDATA <- function() {
    .Call('_hector_MSG_SETDATA', PACKAGE = 'hector')
}

EMISSIONS_BC <- function() {
    .Call('_hector_EMISSIONS_BC', PACKAGE = 'hector')
}

RF_TOTAL <- function() {
    .Call('_hector_RF_TOTAL', PACKAGE = 'hector')
}

RF_T_ALBEDO <- function() {
    .Call('_hector_RF_T_ALBEDO', PACKAGE = 'hector')
}

RF_CO2 <- function() {
    .Call('_hector_RF_CO2', PACKAGE = 'hector')
}

RF_N2O <- function() {
    .Call('_hector_RF_N2O', PACKAGE = 'hector')
}

RF_H2O <- function() {
    .Call('_hector_RF_H2O', PACKAGE = 'hector')
}

RF_O3 <- function() {
    .Call('_hector_RF_O3', PACKAGE = 'hector')
}

RF_BC <- function() {
    .Call('_hector_RF_BC', PACKAGE = 'hector')
}

RF_OC <- function() {
    .Call('_hector_RF_OC', PACKAGE = 'hector')
}

RF_SO2D <- function() {
    .Call('_hector_RF_SO2D', PACKAGE = 'hector')
}

RF_SO2I <- function() {
    .Call('_hector_RF_SO2I', PACKAGE = 'hector')
}

RF_SO2 <- function() {
    .Call('_hector_RF_SO2', PACKAGE = 'hector')
}

RF_VOL <- function() {
    .Call('_hector_RF_VOL', PACKAGE = 'hector')
}

RF_HALOCARBONS <- function() {
    .Call('_hector_RF_HALOCARBONS', PACKAGE = 'hector')
}

RF_CF4 <- function() {
    .Call('_hector_RF_CF4', PACKAGE = 'hector')
}

RF_C2F6 <- function() {
    .Call('_hector_RF_C2F6', PACKAGE = 'hector')
}

RF_HFC23 <- function() {
    .Call('_hector_RF_HFC23', PACKAGE = 'hector')
}

RF_HFC32 <- function() {
    .Call('_hector_RF_HFC32', PACKAGE = 'hector')
}

RF_HFC4310 <- function() {
    .Call('_hector_RF_HFC4310', PACKAGE = 'hector')
}

RF_HFC125 <- function() {
    .Call('_hector_RF_HFC125', PACKAGE = 'hector')
}

RF_HFC134A <- function() {
    .Call('_hector_RF_HFC134A', PACKAGE = 'hector')
}

RF_HFC143A <- function() {
    .Call('_hector_RF_HFC143A', PACKAGE = 'hector')
}

RF_HFC227EA <- function() {
    .Call('_hector_RF_HFC227EA', PACKAGE = 'hector')
}

RF_HFC245FA <- function() {
    .Call('_hector_RF_HFC245FA', PACKAGE = 'hector')
}

RF_SF6 <- function() {
    .Call('_hector_RF_SF6', PACKAGE = 'hector')
}

RF_CFC11 <- function() {
    .Call('_hector_RF_CFC11', PACKAGE = 'hector')
}

RF_CFC12 <- function() {
    .Call('_hector_RF_CFC12', PACKAGE = 'hector')
}

RF_CFC113 <- function() {
    .Call('_hector_RF_CFC113', PACKAGE = 'hector')
}

RF_CFC114 <- function() {
    .Call('_hector_RF_CFC114', PACKAGE = 'hector')
}

RF_CFC115 <- function() {
    .Call('_hector_RF_CFC115', PACKAGE = 'hector')
}

RF_CCL4 <- function() {
    .Call('_hector_RF_CCL4', PACKAGE = 'hector')
}

RF_CH3CCL3 <- function() {
    .Call('_hector_RF_CH3CCL3', PACKAGE = 'hector')
}

RF_HCF22 <- function() {
    .Call('_hector_RF_HCF22', PACKAGE = 'hector')
}

RF_HCF141B <- function() {
    .Call('_hector_RF_HCF141B', PACKAGE = 'hector')
}

RF_HCF142B <- function() {
    .Call('_hector_RF_HCF142B', PACKAGE = 'hector')
}

RF_HALON1211 <- function() {
    .Call('_hector_RF_HALON1211', PACKAGE = 'hector')
}

RF_HALON1301 <- function() {
    .Call('_hector_RF_HALON1301', PACKAGE = 'hector')
}

RF_HALON2402 <- function() {
    .Call('_hector_RF_HALON2402', PACKAGE = 'hector')
}

RF_CH3CL <- function() {
    .Call('_hector_RF_CH3CL', PACKAGE = 'hector')
}

RF_CH3BR <- function() {
    .Call('_hector_RF_CH3BR', PACKAGE = 'hector')
}

EMISSIONS_CF4 <- function() {
    .Call('_hector_EMISSIONS_CF4', PACKAGE = 'hector')
}

EMISSIONS_C2F6 <- function() {
    .Call('_hector_EMISSIONS_C2F6', PACKAGE = 'hector')
}

EMISSIONS_HFC23 <- function() {
    .Call('_hector_EMISSIONS_HFC23', PACKAGE = 'hector')
}

EMISSIONS_HFC32 <- function() {
    .Call('_hector_EMISSIONS_HFC32', PACKAGE = 'hector')
}

EMISSIONS_HFC4310 <- function() {
    .Call('_hector_EMISSIONS_HFC4310', PACKAGE = 'hector')
}

EMISSIONS_HFC125 <- function() {
    .Call('_hector_EMISSIONS_HFC125', PACKAGE = 'hector')
}

EMISSIONS_HFC134A <- function() {
    .Call('_hector_EMISSIONS_HFC134A', PACKAGE = 'hector')
}

EMISSIONS_HFC143A <- function() {
    .Call('_hector_EMISSIONS_HFC143A', PACKAGE = 'hector')
}

EMISSIONS_HFC227EA <- function() {
    .Call('_hector_EMISSIONS_HFC227EA', PACKAGE = 'hector')
}

EMISSIONS_HFC245FA <- function() {
    .Call('_hector_EMISSIONS_HFC245FA', PACKAGE = 'hector')
}

EMISSIONS_SF6 <- function() {
    .Call('_hector_EMISSIONS_SF6', PACKAGE = 'hector')
}

EMISSIONS_CFC11 <- function() {
    .Call('_hector_EMISSIONS_CFC11', PACKAGE = 'hector')
}

EMISSIONS_CFC12 <- function() {
    .Call('_hector_EMISSIONS_CFC12', PACKAGE = 'hector')
}

EMISSIONS_CFC113 <- function() {
    .Call('_hector_EMISSIONS_CFC113', PACKAGE = 'hector')
}

EMISSIONS_CFC114 <- function() {
    .Call('_hector_EMISSIONS_CFC114', PACKAGE = 'hector')
}

EMISSIONS_CFC115 <- function() {
    .Call('_hector_EMISSIONS_CFC115', PACKAGE = 'hector')
}

EMISSIONS_CCL4 <- function() {
    .Call('_hector_EMISSIONS_CCL4', PACKAGE = 'hector')
}

EMISSIONS_CH3CCL3 <- function() {
    .Call('_hector_EMISSIONS_CH3CCL3', PACKAGE = 'hector')
}

EMISSIONS_HCF22 <- function() {
    .Call('_hector_EMISSIONS_HCF22', PACKAGE = 'hector')
}

EMISSIONS_HCF141B <- function() {
    .Call('_hector_EMISSIONS_HCF141B', PACKAGE = 'hector')
}

EMISSIONS_HCF142B <- function() {
    .Call('_hector_EMISSIONS_HCF142B', PACKAGE = 'hector')
}

EMISSIONS_HALON1211 <- function() {
    .Call('_hector_EMISSIONS_HALON1211', PACKAGE = 'hector')
}

EMISSIONS_HALON1301 <- function() {
    .Call('_hector_EMISSIONS_HALON1301', PACKAGE = 'hector')
}

EMISSIONS_HALON2402 <- function() {
    .Call('_hector_EMISSIONS_HALON2402', PACKAGE = 'hector')
}

EMISSIONS_CH3CL <- function() {
    .Call('_hector_EMISSIONS_CH3CL', PACKAGE = 'hector')
}

EMISSIONS_CH3BR <- function() {
    .Call('_hector_EMISSIONS_CH3BR', PACKAGE = 'hector')
}

PREINDUSTRIAL_HC <- function() {
    .Call('_hector_PREINDUSTRIAL_HC', PACKAGE = 'hector')
}

HC_CONCENTRATION <- function() {
    .Call('_hector_HC_CONCENTRATION', PACKAGE = 'hector')
}

HC_EMISSION <- function() {
    .Call('_hector_HC_EMISSION', PACKAGE = 'hector')
}

ATMOSPHERIC_CH4 <- function() {
    .Call('_hector_ATMOSPHERIC_CH4', PACKAGE = 'hector')
}

PREINDUSTRIAL_CH4 <- function() {
    .Call('_hector_PREINDUSTRIAL_CH4', PACKAGE = 'hector')
}

RF_CH4 <- function() {
    .Call('_hector_RF_CH4', PACKAGE = 'hector')
}

EMISSIONS_CH4 <- function() {
    .Call('_hector_EMISSIONS_CH4', PACKAGE = 'hector')
}

NATURAL_CH4 <- function() {
    .Call('_hector_NATURAL_CH4', PACKAGE = 'hector')
}

CONVERSION_CH4 <- function() {
    .Call('_hector_CONVERSION_CH4', PACKAGE = 'hector')
}

LIFETIME_SOIL <- function() {
    .Call('_hector_LIFETIME_SOIL', PACKAGE = 'hector')
}

LIFETIME_STRAT <- function() {
    .Call('_hector_LIFETIME_STRAT', PACKAGE = 'hector')
}

ATMOSPHERIC_N2O <- function() {
    .Call('_hector_ATMOSPHERIC_N2O', PACKAGE = 'hector')
}

PREINDUSTRIAL_N2O <- function() {
    .Call('_hector_PREINDUSTRIAL_N2O', PACKAGE = 'hector')
}

EMISSIONS_N2O <- function() {
    .Call('_hector_EMISSIONS_N2O', PACKAGE = 'hector')
}

NAT_EMISSIONS_N2O <- function() {
    .Call('_hector_NAT_EMISSIONS_N2O', PACKAGE = 'hector')
}

CONVERSION_N2O <- function() {
    .Call('_hector_CONVERSION_N2O', PACKAGE = 'hector')
}

INITIAL_LIFETIME_N2O <- function() {
    .Call('_hector_INITIAL_LIFETIME_N2O', PACKAGE = 'hector')
}

LIFETIME_N2O <- function() {
    .Call('_hector_LIFETIME_N2O', PACKAGE = 'hector')
}

LIFETIME_OH <- function() {
    .Call('_hector_LIFETIME_OH', PACKAGE = 'hector')
}

INITIAL_LIFETIME_OH <- function() {
    .Call('_hector_INITIAL_LIFETIME_OH', PACKAGE = 'hector')
}

COEFFICIENT_NOX <- function() {
    .Call('_hector_COEFFICIENT_NOX', PACKAGE = 'hector')
}

COEFFICIENT_CH4 <- function() {
    .Call('_hector_COEFFICIENT_CH4', PACKAGE = 'hector')
}

COEFFICIENT_NMVOC <- function() {
    .Call('_hector_COEFFICIENT_NMVOC', PACKAGE = 'hector')
}

COEFFICIENT_CO <- function() {
    .Call('_hector_COEFFICIENT_CO', PACKAGE = 'hector')
}

PREINDUSTRIAL_O3 <- function() {
    .Call('_hector_PREINDUSTRIAL_O3', PACKAGE = 'hector')
}

ATMOSPHERIC_O3 <- function() {
    .Call('_hector_ATMOSPHERIC_O3', PACKAGE = 'hector')
}

ATMOSPHERIC_EM_CH4 <- function() {
    .Call('_hector_ATMOSPHERIC_EM_CH4', PACKAGE = 'hector')
}

EMISSIONS_NOX <- function() {
    .Call('_hector_EMISSIONS_NOX', PACKAGE = 'hector')
}

EMISSIONS_CO <- function() {
    .Call('_hector_EMISSIONS_CO', PACKAGE = 'hector')
}

EMISSIONS_NMVOC <- function() {
    .Call('_hector_EMISSIONS_NMVOC', PACKAGE = 'hector')
}

EMISSIONS_OC <- function() {
    .Call('_hector_EMISSIONS_OC', PACKAGE = 'hector')
}

OCEAN_CFLUX <- function() {
    .Call('_hector_OCEAN_CFLUX', PACKAGE = 'hector')
}

OCEAN_C <- function() {
    .Call('_hector_OCEAN_C', PACKAGE = 'hector')
}

TT <- function() {
    .Call('_hector_TT', PACKAGE = 'hector')
}

TU <- function() {
    .Call('_hector_TU', PACKAGE = 'hector')
}

TWI <- function() {
    .Call('_hector_TWI', PACKAGE = 'hector')
}

TID <- function() {
    .Call('_hector_TID', PACKAGE = 'hector')
}

CIRC_TOPT <- function() {
    .Call('_hector_CIRC_TOPT', PACKAGE = 'hector')
}

CIRC_T50_HIGH <- function() {
    .Call('_hector_CIRC_T50_HIGH', PACKAGE = 'hector')
}

CIRC_T50_LOW <- function() {
    .Call('_hector_CIRC_T50_LOW', PACKAGE = 'hector')
}

HL_DO <- function() {
    .Call('_hector_HL_DO', PACKAGE = 'hector')
}

PH_HL <- function() {
    .Call('_hector_PH_HL', PACKAGE = 'hector')
}

PH_LL <- function() {
    .Call('_hector_PH_LL', PACKAGE = 'hector')
}

ATM_OCEAN_FLUX_HL <- function() {
    .Call('_hector_ATM_OCEAN_FLUX_HL', PACKAGE = 'hector')
}

ATM_OCEAN_FLUX_LL <- function() {
    .Call('_hector_ATM_OCEAN_FLUX_LL', PACKAGE = 'hector')
}

PCO2_HL <- function() {
    .Call('_hector_PCO2_HL', PACKAGE = 'hector')
}

PCO2_LL <- function() {
    .Call('_hector_PCO2_LL', PACKAGE = 'hector')
}

DIC_HL <- function() {
    .Call('_hector_DIC_HL', PACKAGE = 'hector')
}

DIC_LL <- function() {
    .Call('_hector_DIC_LL', PACKAGE = 'hector')
}

P0_LL <- function() {
    .Call('_hector_P0_LL', PACKAGE = 'hector')
}

CARBON_HL <- function() {
    .Call('_hector_CARBON_HL', PACKAGE = 'hector')
}

CARBON_LL <- function() {
    .Call('_hector_CARBON_LL', PACKAGE = 'hector')
}

CARBON_IO <- function() {
    .Call('_hector_CARBON_IO', PACKAGE = 'hector')
}

CARBON_DO <- function() {
    .Call('_hector_CARBON_DO', PACKAGE = 'hector')
}

OMEGACA_HL <- function() {
    .Call('_hector_OMEGACA_HL', PACKAGE = 'hector')
}

OMEGACA_LL <- function() {
    .Call('_hector_OMEGACA_LL', PACKAGE = 'hector')
}

OMEGAAR_HL <- function() {
    .Call('_hector_OMEGAAR_HL', PACKAGE = 'hector')
}

OMEGAAR_LL <- function() {
    .Call('_hector_OMEGAAR_LL', PACKAGE = 'hector')
}

TEMP_HL <- function() {
    .Call('_hector_TEMP_HL', PACKAGE = 'hector')
}

TEMP_LL <- function() {
    .Call('_hector_TEMP_LL', PACKAGE = 'hector')
}

SPINUP_CHEM <- function() {
    .Call('_hector_SPINUP_CHEM', PACKAGE = 'hector')
}

CO3_LL <- function() {
    .Call('_hector_CO3_LL', PACKAGE = 'hector')
}

CO3_HL <- function() {
    .Call('_hector_CO3_HL', PACKAGE = 'hector')
}

ATM_OCEAN_CONSTRAIN <- function() {
    .Call('_hector_ATM_OCEAN_CONSTRAIN', PACKAGE = 'hector')
}

TIMESTEPS <- function() {
    .Call('_hector_TIMESTEPS', PACKAGE = 'hector')
}

REVELLE_HL <- function() {
    .Call('_hector_REVELLE_HL', PACKAGE = 'hector')
}

REVELLE_LL <- function() {
    .Call('_hector_REVELLE_LL', PACKAGE = 'hector')
}

LAND_CFLUX <- function() {
    .Call('_hector_LAND_CFLUX', PACKAGE = 'hector')
}

ATMOSPHERIC_CO2 <- function() {
    .Call('_hector_ATMOSPHERIC_CO2', PACKAGE = 'hector')
}

PREINDUSTRIAL_CO2 <- function() {
    .Call('_hector_PREINDUSTRIAL_CO2', PACKAGE = 'hector')
}

ATMOSPHERIC_C <- function() {
    .Call('_hector_ATMOSPHERIC_C', PACKAGE = 'hector')
}

ATMOSPHERIC_C_RESIDUAL <- function() {
    .Call('_hector_ATMOSPHERIC_C_RESIDUAL', PACKAGE = 'hector')
}

EARTHC <- function() {
    .Call('_hector_EARTHC', PACKAGE = 'hector')
}

VEGC <- function() {
    .Call('_hector_VEGC', PACKAGE = 'hector')
}

DETRITUSC <- function() {
    .Call('_hector_DETRITUSC', PACKAGE = 'hector')
}

SOILC <- function() {
    .Call('_hector_SOILC', PACKAGE = 'hector')
}

FFI_EMISSIONS <- function() {
    .Call('_hector_FFI_EMISSIONS', PACKAGE = 'hector')
}

LUC_EMISSIONS <- function() {
    .Call('_hector_LUC_EMISSIONS', PACKAGE = 'hector')
}

CO2FERT <- function() {
    .Call('_hector_CO2FERT', PACKAGE = 'hector')
}

TEMPFERTD <- function() {
    .Call('_hector_TEMPFERTD', PACKAGE = 'hector')
}

TEMPFERTS <- function() {
    .Call('_hector_TEMPFERTS', PACKAGE = 'hector')
}

Q10_RH <- function() {
    .Call('_hector_Q10_RH', PACKAGE = 'hector')
}

NPP <- function() {
    .Call('_hector_NPP', PACKAGE = 'hector')
}

RH <- function() {
    .Call('_hector_RH', PACKAGE = 'hector')
}

F_NPPV <- function() {
    .Call('_hector_F_NPPV', PACKAGE = 'hector')
}

F_NPPD <- function() {
    .Call('_hector_F_NPPD', PACKAGE = 'hector')
}

F_LITTERD <- function() {
    .Call('_hector_F_LITTERD', PACKAGE = 'hector')
}

F_LUCV <- function() {
    .Call('_hector_F_LUCV', PACKAGE = 'hector')
}

F_LUCD <- function() {
    .Call('_hector_F_LUCD', PACKAGE = 'hector')
}

NPP_FLUX0 <- function() {
    .Call('_hector_NPP_FLUX0', PACKAGE = 'hector')
}

CA_CONSTRAIN <- function() {
    .Call('_hector_CA_CONSTRAIN', PACKAGE = 'hector')
}

BETA <- function() {
    .Call('_hector_BETA', PACKAGE = 'hector')
}

WARMINGFACTOR <- function() {
    .Call('_hector_WARMINGFACTOR', PACKAGE = 'hector')
}

SL_RC <- function() {
    .Call('_hector_SL_RC', PACKAGE = 'hector')
}

SLR <- function() {
    .Call('_hector_SLR', PACKAGE = 'hector')
}

SL_RC_NO_ICE <- function() {
    .Call('_hector_SL_RC_NO_ICE', PACKAGE = 'hector')
}

SLR_NO_ICE <- function() {
    .Call('_hector_SLR_NO_ICE', PACKAGE = 'hector')
}

NATURAL_SO2 <- function() {
    .Call('_hector_NATURAL_SO2', PACKAGE = 'hector')
}

D2000_SO2 <- function() {
    .Call('_hector_D2000_SO2', PACKAGE = 'hector')
}

EMISSIONS_SO2 <- function() {
    .Call('_hector_EMISSIONS_SO2', PACKAGE = 'hector')
}

VOLCANIC_SO2 <- function() {
    .Call('_hector_VOLCANIC_SO2', PACKAGE = 'hector')
}

ECS <- function() {
    .Call('_hector_ECS', PACKAGE = 'hector')
}

GLOBAL_TEMP <- function() {
    .Call('_hector_GLOBAL_TEMP', PACKAGE = 'hector')
}

GLOBAL_TEMPEQ <- function() {
    .Call('_hector_GLOBAL_TEMPEQ', PACKAGE = 'hector')
}

TGAV_CONSTRAIN <- function() {
    .Call('_hector_TGAV_CONSTRAIN', PACKAGE = 'hector')
}

SO2D_B <- function() {
    .Call('_hector_SO2D_B', PACKAGE = 'hector')
}

SO2I_B <- function() {
    .Call('_hector_SO2I_B', PACKAGE = 'hector')
}

OC_B <- function() {
    .Call('_hector_OC_B', PACKAGE = 'hector')
}

BC_B <- function() {
    .Call('_hector_BC_B', PACKAGE = 'hector')
}

DIFFUSIVITY <- function() {
    .Call('_hector_DIFFUSIVITY', PACKAGE = 'hector')
}

AERO_SCALE <- function() {
    .Call('_hector_AERO_SCALE', PACKAGE = 'hector')
}

FLUX_MIXED <- function() {
    .Call('_hector_FLUX_MIXED', PACKAGE = 'hector')
}

FLUX_INTERIOR <- function() {
    .Call('_hector_FLUX_INTERIOR', PACKAGE = 'hector')
}

HEAT_FLUX <- function() {
    .Call('_hector_HEAT_FLUX', PACKAGE = 'hector')
}

#' Create and initialize a new hector instance
#'
#' The object returned is a handle to the newly created instance.  It will be required as an
#' argument for all functions that operate on the instance.  Creating multiple instances
#' simultaneously is supported.
#'
#' @param infile (String) name of the hector input file.
#' @return handle for the Hector instance.
#' @export
newcore <- function(inifile) {
    .Call('_hector_newcore', PACKAGE = 'hector', inifile)
}

#' Shutdown a hector instance
#'
#' Shutting down an instance will free the instance itself and all of the objects it created. Any attempted
#' operation on the instance after that will raise an error.
#'
#' @section Caution:
#' This function should be called as \code{mycore <- shutdown(mycore)} so that the change
#' from active to inactive will be recorded in the caller.
#'
#' @param Handle to the Hector instance that is to be shut down.
#' @return The Hector handle, modified to show that it is no longer active.
#' @export
shutdown <- function(core) {
    .Call('_hector_shutdown', PACKAGE = 'hector', core)
}

#' Run the Hector climate model
#'
#' Run Hector up through the specified time.  This function does not return the results
#' of the run.  To get results, run \code{fetch}.
#'
#' @param core Handle a Hector instance that is to be run.
#' @param runtodate Date to run to.  The default is to run to the end date configured
#' in the input file used to initialize the core.
#' @export
run <- function(core, runtodate = -1.0) {
    invisible(.Call('_hector_run', PACKAGE = 'hector', core, runtodate))
}

#' Get the current date for a Hector instance
#'
#' The "current date" is the last year that the Hector instance has completed.
#'
#' @param core Handle to a Hector instance
#' @return The current date in the Hector instance
#' @export
getdate <- function(core) {
    .Call('_hector_getdate', PACKAGE = 'hector', core)
}

#' Send a message to a Hector instance
#'
#' Messages are the mechanism used to get data from Hector model components and
#' to set values within components.
#' 
#' A message comprises a type (e.g. GETDATA to retrieve data from a component, or SETDATA to
#' set data in a component), a capability, which identifies the information to be operated
#' on (e.g. Atmospheric CO2 concentration, or global total radiative forcing), and an optional
#' structure of extra data (comprising a date and a numerical value with units).
#'
#' The arguments to this function are organized in a slightly more R-friendly way.  The message
#' type and capability are each passed as a single string.  The date portion of the extra
#' data is passed as a numeric vector (one message will be generated for each date).  The value
#' portion of the extra data is a numeric vector with a length of either 1 or the same length
#' as the date vector.  The units portion is a single string (we don't support sending a vector
#' of values with heterogeneous units in a single call.
#'
#' Either the date or the value (or both) may be NA.  The date should be NA in cases where the
#' parameter being referenced doesn't change with time.  The value should be NA in cases where
#' the optional data will be ignored.
#'
#' @param core a Hector instance
#' @param msgtype (String) type of message. Usually either GETDATA or SETDATA
#' @param capability (String) capability being targeted by the message.  The core will use
#' this information to look up the component to route the message to.
#' @param date (NumericVector) Date for which to set/get the variable.  Use NA if there is
#' no applicable date.
#' @param value (NumericVector) Numeric portion of the optional data (in case of setting
#' a value this will be the value to set).  The length of this vector should match that of
#' the time, or it should be length 1 (in which case it will be recycled).
#' @param unit (String) Unit for the value vector.
#' @export
sendmessage <- function(core, msgtype, capability, date, value, unit) {
    .Call('_hector_sendmessage', PACKAGE = 'hector', core, msgtype, capability, date, value, unit)
}

