# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create and initialize a new hector instance
#'
#' The object returned is a handle to the newly created instance.  It will be required as an
#' argument for all functions that operate on the instance.  Creating multiple instances
#' simultaneously is supported.
#'
#' @param infile (String) name of the hector input file.
#' @return handle for the Hector instance.
#' @export
newcore <- function(inifile) {
    .Call('_hector_newcore', PACKAGE = 'hector', inifile)
}

#' Shutdown a hector instance
#'
#' Shutting down an instance will free the instance itself and all of the objects it created. Any attempted
#' operation on the instance after that will raise an error.
#'
#' @section Caution:
#' This function should be called as \code{mycore <- shutdown(mycore)} so that the change
#' from active to inactive will be recorded in the caller.
#'
#' @param Handle to the Hector instance that is to be shut down.
#' @return The Hector handle, modified to show that it is no longer active.
#' @export
shutdown <- function(core) {
    .Call('_hector_shutdown', PACKAGE = 'hector', core)
}

#' Run the Hector climate model
#'
#' Run Hector up through the specified time.  This function does not return the results
#' of the run.  To get results, run \code{fetch}.
#'
#' @param core Handle a Hector instance that is to be run.
#' @param runtodate Date to run to.  The default is to run to the end date configured
#' in the input file used to initialize the core.
#' @export
run <- function(core, runtodate = -1.0) {
    invisible(.Call('_hector_run', PACKAGE = 'hector', core, runtodate))
}

#' Get the current date for a Hector instance
#'
#' The "current date" is the last year that the Hector instance has completed.
#'
#' @param core Handle to a Hector instance
#' @return The current date in the Hector instance
#' @export
getdate <- function(core) {
    .Call('_hector_getdate', PACKAGE = 'hector', core)
}

#' Send a message to a Hector instance
#'
#' Messages are the mechanism used to get data from Hector model components and
#' to set values within components.
#' 
#' A message comprises a type (e.g. GETDATA to retrieve data from a component, or SETDATA to
#' set data in a component), a capability, which identifies the information to be operated
#' on (e.g. Atmospheric CO2 concentration, or global total radiative forcing), and an optional
#' structure of extra data (comprising a date and a numerical value with units).
#'
#' The arguments to this function are organized in a slightly more R-friendly way.  The message
#' type and capability are each passed as a single string.  The date portion of the extra
#' data is passed as a numeric vector (one message will be generated for each date).  The value
#' portion of the extra data is a numeric vector with a length of either 1 or the same length
#' as the date vector.  The units portion is a single string (we don't support sending a vector
#' of values with heterogeneous units in a single call.
#'
#' Either the date or the value (or both) may be NA.  The date should be NA in cases where the
#' parameter being referenced doesn't change with time.  The value should be NA in cases where
#' the optional data will be ignored.
#'
#' @param core a Hector instance
#' @param msgtype (String) type of message. Usually either GETDATA or SETDATA
#' @param capability (String) capability being targeted by the message.  The core will use
#' this information to look up the component to route the message to.
#' @param date (NumericVector) Date for which to set/get the variable.  Use NA if there is
#' no applicable date.
#' @param value (NumericVector) Numeric portion of the optional data (in case of setting
#' a value this will be the value to set).  The length of this vector should match that of
#' the time, or it should be length 1 (in which case it will be recycled).
#' @param unit (String) Unit for the value vector.
#' @export
sendmessage <- function(core, msgtype, capability, date, value, unit) {
    .Call('_hector_sendmessage', PACKAGE = 'hector', core, msgtype, capability, date, value, unit)
}

