name: test-coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 1 * *'  # Run at 6 AM on the 1st of each month
  workflow_dispatch:

jobs:
  test-coverage:
    # Don't run scheduled job on forks, only in the main repository.
    if: (github.event_name == 'schedule' && github.repository == 'JGCRI/hector') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4  # Updated to v4

      # Set up R environment
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      # Set up Pandoc
      - uses: r-lib/actions/setup-pandoc@v2

      # Query dependencies and save them for caching
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      # Cache R packages to speed up subsequent runs
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('.github/depends.Rds') }}  # Correct placement of hashFiles
          restore-keys: r-

      # Install necessary system dependencies
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev

      # Install R dependencies
      - name: Install R dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      # Run tests and send coverage report
      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
