# This is a basic workflow to help you get started with Actions
# based on https://github.com/JGCRI/hector/new/master?filename=.github%2Fworkflows%2Fmain.yml&workflow_template=blank

name: Command Line Hector

# Controls when the action will run.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**' # matches every branch

  schedule:
    # * is a special character in YAML so you have to quote this string
    # Launch run at 6am the 1st of every month.
    - cron:  '0 6 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains two jobs, one that builds hector on ubuntu and the second
  # builds and tests Hector on macos. The purpose of this work for is to make sure that Hector
  # can be built from the command line.
  ubuntu:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build and run
        run: |
          sudo apt-get update
          sudo apt install libboost-dev
          make hector
          bash ./test_hector.sh ./src/hector
