name: Run command line and C++ unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 6 1 * *'  # Run at 6am on the 1st of every month
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (e.g., Debug or Release)'
        required: false
        default: 'Release'
      verbose_logs:
        description: 'Enable verbose logging? (true/false)'
        required: false
        default: 'false'

jobs:
  build:
    if: github.event_name != 'schedule' || github.repository == 'JGCRI/hector'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Cache dependencies for Boost and GTest (shared between both tasks)
      - name: Cache Boost and GTest Dependencies
        uses: actions/cache@v3
        with:
          path: /usr/local/lib /usr/local/include
          key: ${{ runner.os }}-boost-gtest-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-boost-gtest-

      # Install dependencies if not found in cache
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev libgtest-dev
          # Build GTest if needed (in case it's not cached)
          if [ ! -f /usr/local/lib/libgtest.a ]; then
            cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/local/lib
          fi

      # Build and run Hector (for both regular and unit tests)
      - name: Build and Run Hector
        run: |
          make hector
          bash ./test_hector.sh ./src/hector

      # Build and run unit tests if on the main branch or other events
      - name: Build and Run Unit Tests
        run: |
          set -e
          BOOSTROOT=/usr/local/
          GTROOT=/usr/local/
          BUILD_TYPE=${{ github.event.inputs.build_type }}
          VERBOSE=${{ github.event.inputs.verbose_logs }}

          echo "Build Type: $BUILD_TYPE"
          if [ "$VERBOSE" == "true" ]; then
            echo "Running in verbose mode..."
            make VERBOSE=1 testing
          else
            make testing
          fi

          ./src/unit-testing/hector-unit-tests
