# Build the gtest Hector and run it

name: googletest Hector

# Controls when the action will run.
on:
  push:
    branches:
      - master
      - github_actions
  pull_request:
    branches: master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains one job that builds hector on ubuntu using the 
  # googletest framework.
  ubuntu:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install gtest
      # following https://github.com/bastianhjaeger/github_actions_gtest_example
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib 
      - name: Install Boost
        run: sudo apt install libboost-filesystem-dev libboost-system-dev
      - name: build and run
        run: |
          ver=`awk '/define.*BOOST_LIB_VERSION/ {print $3}' /usr/include/boost/version.hpp`
          echo Boost version $ver
          GTLIB=/usr/lib
          GTINC=
          BOOSTLIB=/usr/local/lib BOOSTVERSION=$ver BOOSTROOT=/usr/include/boost 
          make hector
          bash ./test_hector.sh ./src/hector
