name: Leeyabot Report

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  pull_request:
    paths:
      - "scripts/leeyabot.Rmd"  # Runs when report.Rmd changes in a PR

jobs:
  render-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install System Dependencies (including Pandoc)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install -y libjs-mathjax

      - name: Cache R Packages
        uses: actions/cache@v3
        with:
          path: ~/.local/share/R/  # Default library path for R on Ubuntu
          key: r-packages-${{ runner.os }}-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            r-packages-${{ runner.os }}-

      - name: Install dependencies
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("ggplot2", "rmarkdown", "dplyr", "remotes", "here", "knitr", "Rcpp", "BH"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Render RMarkdown
        run: R -e 'rmarkdown::render("scripts/leeyabot.Rmd", output_format="github_document")'

      - name: Comment Report on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
            issue-number: ${{ github.event.pull_request.number }}
            body: |
                :bar_chart: **Leeyabot Report Generated** :robot:

                Here is the latest automated report:

                ```
                 $(cat scripts/leeyabot.md)
                ```

                :chart_with_upwards_trend: *Figures generated are available in the PR.*
            reactions: "+1"
