# This is a temporary test to help with debugging the enviornment problems with
# the github actions
name: R-devtools-build
# Controls when the action will run.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**' # matches every branch

  schedule:
    # * is a special character in YAML so you have to quote this string
    # Launch run at 6am the 1st of every month.
    - cron:  '0 6 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  R-devtools-build:
    # Don't run scheduled job on forks, only in main repository.
    if: (github.event_name == 'schedule' && github.repository == 'JGCRI/hector') || (github.event_name != 'schedule')

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install BH 1.84.0
        run: Rscript -e 'install.packages("BH", version = "1.84.0", repos = "http://cran.us.r-project.org")'

      - name: Install devtools
        run: Rscript -e 'install.packages("devtools", repos = "http://cran.us.r-project.org")'

      - name: Run devtools::build()
        run: Rscript -e 'devtools::build()'
