name: test command line hector
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        - name: Compile
      		run: |
        	sudo apt install libboost-filesystem-dev libboost-system-dev
		make hector
