name: test command line hector 
on: [push]
jobs:
  build_hector:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: brew install boost
      - run: make hector
      - run: sh ./test_hector.sh ./src/hector
        env:
          BOOSTROOT: /usr/local/Cellar/boost/1.74.0/include
          BOOSTLIB: /usr/local/Cellar/boost/1.74.0/lib
          
          
