# Build the gtest Hector and run it

name: C++ unit tests

on:
  pull_request:
    branches:
      - '**' # matches every branch

  # Manual trigger with optional inputs
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (e.g., Debug or Release)'
        required: false
        default: 'Release'
      verbose_logs:
        description: 'Enable verbose logging? (true/false)'
        required: false
        default: 'false'

  # Scheduled run on the first of every month at 00:00 UTC
  schedule:
    - cron: '0 0 1 * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' || github.event_name != 'schedule'

    steps:
      - uses: actions/checkout@v3

      - name: Install gtest
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/local/lib

      - name: Install Boost
        run: sudo apt install libboost-filesystem-dev libboost-system-dev

      - name: Build and run tests
        run: |
          set -e
          BOOSTROOT=/usr/local/
          GTROOT=/usr/local/
          BUILD_TYPE=${{ github.event.inputs.build_type }}
          VERBOSE=${{ github.event.inputs.verbose_logs }}

          echo "Build Type: $BUILD_TYPE"
          if [ "$VERBOSE" == "true" ]; then
            echo "Running in verbose mode..."
            make VERBOSE=1 testing
          else
            make testing
          fi

          ./src/unit-testing/hector-unit-tests
