# Build the gtest Hector and run it

name: C++ unit tests

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '**' # matches every branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains one job that builds hector on ubuntu using the
  # googletest framework.
  ubuntu:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install gtest
      # based on https://github.com/bastianhjaeger/github_actions_gtest_example
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/local/lib
      - name: Install Boost
        run: sudo apt install libboost-filesystem-dev libboost-system-dev
      - name: build and run
      # NB we don't really need to define BOOSTROOT and GTROOT; these are the defaults
        run: |
          BOOSTROOT=/usr/local/
          GTROOT=/usr/local/
          make testing
          ./src/unit-testing/hector-unit-tests
